### ISSUE TITLE
LimLog: async mmap

### ISSUE THREAD

**Issue by George-Miao** [Limit-LAB/limlog#11]
## Design

- mmap data with [`memmap2`](https://docs.rs/memmap2)
- mmap-ed files should be flock-ed to avoid being truncated, which will cause `SIGBUS` 
- An offset represented by an `AtomicUsize` (shared among appender and reader) 

### Appender

- Only one per mmap
- Holds [`MmapRaw`](https://docs.rs/memmap2/latest/memmap2/struct.MmapRaw.html), which will close the mmap on drop
- Update offset logs are written (commit)
- On commit, notify readers with [event_listener](https://docs.rs/event-listener) 
- Implements [`Sink`](https://docs.rs/futures/latest/futures/sink/trait.Sink.html) 
- Derives readers by subscribing
- Writes to index files at the same time

### Reader

- Exists multiple, all with access to immutable part of mmap-ed memory
- Once waked by appender, make progress (read new item)
- Implements [`Stream`](https://docs.rs/futures/latest/futures/stream/trait.Stream.html)
- Implements `Clone`

## Issue

- How to change file once writing completed?

**Comment by ho-229** [comment]
A sample draft of usage is as follows:

```rust
let mut log1 = Limlog::new("./logs")
    .config(
        Config::default()
            .file_size_threshold(500 * 1024 * 1024)
    );

// or log1.feed(Log { uuid: uuid7(), key: vec![], value: vec![] }).await?;
log1.feed(vec![Log { uuid: uuid7(), key: vec![], value: vec![] }]).await?; // write logs to buffer
log1.flush().await?;  // flush to disk

log1.select_logs(Timestamp(0, now_ts))?;
let res: Option<Vec<Log>> = log1.next().await?;

let log2 = log1.clone();   // reference of log1
// ...
```

**Comment by George-Miao** [comment]
We need topic. Also, readers and writer should be able to use async (Stream and Sink), and select with only start point (subscribe to all upcoming event).

**Comment by ho-229** [comment]
`Limlog` already implements Stream and Sink in this case.

**Comment by George-Miao** [comment]
The ideal use case I'm thinking:

```rust
let mut log = Log::builder().file_size_threshold(500 * 1 << 20).build("./logs")?;

let mut topic = log.topic("my_foo_bar_topic")?; // This will create a dir under ./logs

// Topic will be in charge of managing mmaps, while readers have shared access to mmap data and 
// writes are channel senders (to background task where the unique appender recv from channel 
// and write it to the mmap)  
let (mut r, mut w) =  (topic.reader(), topic.writer()); 

tokio::spawn(async move {
  loop {
    w.send(FooBar).await?;
  }

  Ok((
})

while let Some(msg) = r.next().await {
  println!("{msg:?}")
}
```

**Comment by ho-229** [comment]
What's the default starting point for `Topic::reader()`

**Comment by George-Miao** [comment]
> What's the default starting point for `Topic::reader()`

Now

**Comment by George-Miao** [comment]
So whenever a reader is polled, it will check if the slice is still valid (in case the file is completed means no more data, by reading some atomic number with bitflags). If now, it will request the proper slice and offset again.

**Comment by ho-229** [comment]
You can call `madvise()` with `MADV_DONTNEED` flag on UNIX to suggest OS to free the physical memory, the alternative on Windows is `VirtualFree` with `MEM_DECOMMIT` flag.
