### ISSUE TITLE
LimLog: investigate mmap and cache solutions

### ISSUE THREAD

**Issue by LemonHX** [Limit-LAB/limlog#7]
using `mmap` for cache and new multicore read write backend?

**Comment by George-Miao** [comment]
Closed in favor of #11

**Comment by ho-229** [comment]
You can call `madvise()` with `MADV_DONTNEED` flag on UNIX to suggest OS to free the physical memory, the alternative on Windows is `VirtualFree` with `MEM_DECOMMIT` flag.
